version: '3.8'

services:
  mongo_db:
    image: mongo:6.0.5
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - my-mongo-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express-admin
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017/
    ports:
      - 8081:8081
volumes:
  my-mongo-data:
    name: my-mongo-data
networks:
  default:
    name: mongodb_network